spring:
  application:
    name: analytics-service
  cloud:
    stream:
      function:
        definition: meter
      bindings:
        meter-in-0:
          destination: meter.readings
          group: analytics-group

server:
  port: 0
