spring:
  application:
    name: analytics-service
  cloud:
    stream:
      function:
        definition: ${function.chain}
      bindings:
        price|tax|discount-in-0:
          destination: meter.readings
          group: analytics-group
          consumer:
            auto-startup: true
        price|tax|discount-out-0:
          destination: analytics.readings
          content-type: application/json

server:
  port: 0

pricing:
  base-rate: 2.25

function:
  chain: price|tax|discount
