spring:
  application:
    name: meter-service
  cloud:
    stream:
      function:
        definition: meter
      bindings:
        meter-out-0:
          destination: meter.readings
          content-type: application/json

server:
  port: 0

pricing:
  base-rate: 2.25
